config/routes.rb
Rails.application.routes.draw do

  get 'cart' =>  'cart#show'
  post 'cart/add'
  post 'cart/remove'

  resources :items
  get 'itemx' => 'item#index'
  get 'users/index'
  resources :contents
  devise_for :users

 
  # controller pages
  root 'pages#home'
  
  get 'about' => 'pages#about'

  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/content.rb
class Content < ApplicationRecord

    extend FriendlyId
    friendly_id :titolo, use: :slugged
    
    belongs_to :user

    has_many :sales

    has_attached_file :cover, styles: { medium: "300x300>", thumb: "150x100>" } 
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
    message: "Solo le immagini consentite"

    has_attached_file :allegato  
    validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ], 
    message: "Formato non supportato"

    validates :titolo, :descrizione, :price,  presence: true
    validates :price, numericality: { greater_than: 49 }
    validates :cover, attachment_presence: true
    validates :allegato, attachment_presence: true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord
    belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contents

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller? 

         protected

    def configure_permitted_parameters
         devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
         devise_parameter_sanitizer.permit(:account_update, keys: [:name])

    end  

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [ :edit, :update,  :destroy ]

  # GET /contents or /contents.json
  def index
     @contents = Content.all.order("created_at DESC").paginate(:page  => params[:page], :per_page => 3)
     
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    #@content = Content.new
     @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents or /contents.json
  def create
  #@content = Content.new(content_params)
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Contenuto creato correttamente." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Contenuto aggiornato con successo." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Contenuro definitivamene eliminato." }
      format.json { head :no_content }
    end
  end

  def acceptable_image
    return unless main_image.attached?
  
    unless main_image.blob.byte_size <= 1.megabyte
      errors.add(:main_image, "is too big")
    end
  end

  
  
  
  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.friendly.find(params[:id])
    end
 
    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    
 def check_user
  if current_user != @content.user
    redirect_to root_url, alert: "Non hai accesso al contenuto"
  end
 end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :category)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  @users = User.all
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/e.html.erb
<h1>Cart#e</h1>
<p>Find me in app/views/cart/e.html.erb</p>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <p>
    <strong>Titolo:</strong>
    <%= content.titolo %>
  </p>

  <p>
    <strong>Descrizione:</strong>
    <%= content.descrizione %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= content.price %>
  </p>


 </div>

app/views/contents/_form.html.erb
<%= form_for @content, html: { multipart: true } do |form| %>
  <% if content.errors.any? %>
    <div style="color: red">
      <p><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="borderato">
  <br>
 <p class="form_all">Carica il contenuto/articolo che vuoi mettere in vendita (formati supportati: Powerpoint, Excel, PDF, Word, Immagini e Mp3)</p> 
  <%= form.file_field :allegato %>
  <br>
  <br>
  </div>
  <br>
  <div>
    <%= form.label :titolo, style: "display: block" %>
    <%= form.text_field :titolo %>
  </div>

  <div>
    <%= form.label :descrizione, style: "display: block" %>
    <%= form.text_area :descrizione, class: "materialize-textarea" %>
  </div>
  
  <div>
    <%= form.label :prezzo_min_50_cent, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <div class="borderato">
  <p class="form_all">Carica un'immagine da utilizzare per il tuo contenuto/articolo </p>
  <%= form.file_field :cover  %><br>
  <br>
  </div>
 
  <br><br>
  <div>
    <%= form.submit 'Salva Contenuto' , class: "btn  light-blue darken-3" %>
  </div>
  <br>
<% end %>

app/views/contents/_list.html.erb
<div id="<%= dom_id list %>">
<div class="row">

      <div class="col s3">
      <strong>Titolox:</strong>
      </div>
      <div class="col s6">
      <strong>Descrizione:</strong>
      </div>
      <div class="col s3">
      <strong>Prezzo:</strong>
      </div>

 </div>
 <hr>
 <div class="row">

      <div class="col s3">
      <%= content.titolo %>
      </div>
      <div class="col s6">
      <%= content.descrizione %>
      </div>
      <div class="col s3">
      <%= content.price %>
      </div>

 </div>
   

</div>

app/views/contents/edit.html.erb
<h1 class="center">Modifica Articolo  "<%= @content.titolo %>"</h1>
 


<br>
<%= render "form", content: @content %>

<br>

<div >
  <%= link_to "Scheda Articolo", @content, class: "btn" %> &nbsp;
  <%= link_to "Torna a Shop", contents_path , class: "btn" %>
</div>

app/views/contents/index.html.erb
<p style="color: green"><%= notice %></p>
 
 
 
 <br>
<div id="contents">
 
<div class="row">

   
    <% @contents.each do |try|    %>

      <div class="col s4">
              <div class="card">
                         <div class="card-image waves-effect waves-block waves-light">
                         <%= image_tag try.cover.url(:medium) %>
                              
                          </div>
                          <div class="card-content">
                               <span class="card-title activator grey-text text-darken-4" style="text-transform:capitalize !important"> <%= try.titolo %><i class="material-icons right">more_vert</i></span></span>

                          <div> <span class="right" style="padding-right:10px !important">  <%= number_to_currency(try.price) %></span> Venduto da    <%= try.user.name %>
                       
                      </div>
                        </div>
                      
                      <div class="card-action" style="text-align:center;">
                        <a href="#"> <%= link_to "Scopri di più", try , class: "btn" %></a>
                        
                      </div>
              </div>

      </div>
    <%    end %>
  </div>
        


 
</div>
<hr>
<div class="center">
<%= will_paginate @contents, :previous_label => '<<', :next_label => '>>' %>     
</div>
 

app/views/contents/new.html.erb
<h1 class="center">Vendi Nuovo Articolo/Contenuto</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Torna a Shop", contents_path, class: "btn lbtn"%>
</div>

app/views/contents/show.html.erb
<p style="color: green"><%= notice %></p>
<p>&nbsp;</p>
<div class="row">
        <div class="col l6">
             <%= image_tag @content.cover.url, class: "responsive-img show-img" %>
        </div>

        <div class="col l6 ">

              <h1 class="show-titolo"><%= @content.titolo %></h1>
              <h4 class="show-price"><%= number_to_currency(@content.price) %>
              </h4>
              <p class="show-p"> <b>Venduto da: </b> <%= @content.user.name %> </p>

              <p class="show-p"> <b>Descrizione: </b> <br><%= @content.descrizione %>
              </p>


        </div>
             

              
</div>
 

<div style="display:flex;">

  <% if @content.user == current_user%>
  <br>  <%= link_to "Torna a Shop", contents_path , class: "btn"%>  
  &nbsp;  &nbsp; 
   <%= link_to "Modifica", edit_content_path(@content), class: "btn" %> &nbsp;  
  <% end %> &nbsp; 

  <% if @content.user == current_user%>
 
  
  <%= button_to "Elimina", @content, method: :delete, data: { turbo_confirm: 'Sei sicuro di cancellare?'} , class: "btn red darken-2" %>
  <p>&nbsp;</p>
  <% end %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.number_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= item.category %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer  light-blue darken-3" style="padding-top: 0 !important">
<div class="container" style="display:none !important">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">Footer Content</h5>
      <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Links</h5>
      <ul>
        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright  light-blue darken-3">
  <div class="container">
  <div class="row">
      <div class="col s4">
      © 2023 Copyright Alexjweb
      </div>
      <div class="col s4">
        Social
      </div>
      <div class="col s4">
            <%= link_to "About" , about_path, class: "grey-text text-lighten-4 right" %>
      </div>

    </div>  
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">

<nav class=" light-blue darken-3">
  <div class="container nav-wrapper">
  <%= link_to "X-Shop" , root_path, class: "brand-logo" %>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>

    <ul class="right hide-on-med-and-down">
        <li><%= link_to "Vendi contenuto", new_content_path  %></li>
        <li><%= link_to "About" , about_path %></li>
        <li><a href="/contents">Shop</a>xx </li>
  
    <% if user_signed_in? %>
        <li><%= link_to "Logout" , destroy_user_session_path, method: :delete %></li>
    <% else %>
        <li><%= link_to "Login" , new_user_session_path %></li>
        <li><%= link_to "Registrati" , new_user_registration_path %></li>
    <% end  %>
    
  </ul>
 
  </div>
  </nav>
  
  </header>
  <ul class="sidenav" id="mobile-demo">
  <li><%= link_to "Vendi contenuto", new_content_path  %></li>
  <li><%= link_to "About" , about_path %> </li>
  <li><a href="/contents">Shop</a>xx </li>
      
          <% if user_signed_in? %>
              <li><%= link_to "Logout" , destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Login" , new_user_session_path %></li>
              <li><%= link_to "Registrati" , new_user_registration_path %></li>
          <% end  %>
          
    </ul>
    <script>
    M.AutoInit();
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems);
    });
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

 

<!-- Google Materalize fonts -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <style>
    .container{
      max-width:2560px !important;

    }

    </style>
    <script
    src="https://code.jquery.com/jquery-3.7.1.js"
    integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
    crossorigin="anonymous"></script>
		
   
  </head>

  <body >
 
  <%= render "layouts/header" %>
  
  <main  class="container">
  <p class="notice" ><%= notice %></p>
  <p class="alert"><%= alert %></p>                                                                                                        

    <%= yield %>
  </main>
    <%= render "layouts/footer" %>
   
  </body>
  <script>

 
   
  </script>
</html>

app/views/pages/about.html.erb
 
<h1>Chi Siamo</h1>
<p>Siamo un team di persone che studiano Rails</p>

app/views/pages/home.html.erb
 


<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
 

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">Rails Shopping</h1>
        <div class="row center">
          <h5 class="header col s12 light">Un negozio Linux/Ubuntu su Ruby on Rails e Materialize </h5>
        </div>
        <div class="row center">
          <a href="/contents" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Inizia Qui</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="yugi_1920.jpg" alt="Unsplashed background img 1"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Spedizione Veloce Certificata</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Sicurezza dei pagamenti</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Gamma completa prodotti</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Un negozio Linux/Ubuntu su Ruby on Rails e Materialize</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="pokemon_1920.jpg" alt="Unsplashed background img 2"></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Chiama il nostro help-desk e trova subito la tua soluzione</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Un negozio Linux/Ubuntu su Ruby on Rails e Materialize</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="magic_1920.jpg" alt="Unsplashed background img 3"></div>
  </div>

  

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>